import { Amplify } from "aws-amplify";

/**
 * Amplify v6 runtime configuration, built from EXPO_PUBLIC_* env vars.
 *
 * Why env vars and not `import outputs from "../amplify_outputs.json"`? That file
 * is generated by `npx ampx sandbox`, is gitignored, and does not exist until the
 * backend is deployed — a static import of it would break the Metro bundle today.
 * Reading from env is bundle-safe and lets the Supabase build run untouched.
 *
 * After deploying, copy these from amplify_outputs.json into .env:
 *   user_pool_id            → EXPO_PUBLIC_COGNITO_USER_POOL_ID
 *   user_pool_client_id     → EXPO_PUBLIC_COGNITO_APP_CLIENT_ID
 *   identity_pool_id        → EXPO_PUBLIC_COGNITO_IDENTITY_POOL_ID
 *   data.url                → EXPO_PUBLIC_APPSYNC_ENDPOINT
 */
const region = process.env.EXPO_PUBLIC_AWS_REGION ?? "ap-southeast-2";
const userPoolId = process.env.EXPO_PUBLIC_COGNITO_USER_POOL_ID ?? "";
const userPoolClientId = process.env.EXPO_PUBLIC_COGNITO_APP_CLIENT_ID ?? "";
const identityPoolId = process.env.EXPO_PUBLIC_COGNITO_IDENTITY_POOL_ID ?? "";
const graphqlEndpoint = process.env.EXPO_PUBLIC_APPSYNC_ENDPOINT ?? "";
const graphqlApiKey = process.env.EXPO_PUBLIC_APPSYNC_API_KEY ?? "";

/** True once real Cognito values are present (i.e. the backend is deployed). */
export const isAwsConfigured = Boolean(userPoolId && userPoolClientId);

let configured = false;

/**
 * Configure Amplify once. No-ops (returns false) when AWS isn't configured, so
 * importing/calling this on the Supabase build is harmless.
 */
export function configureAmplify(): boolean {
  if (configured) return true;
  if (!isAwsConfigured) return false;

  const api = graphqlEndpoint
    ? {
        API: {
          GraphQL: {
            endpoint: graphqlEndpoint,
            region,
            defaultAuthMode: "userPool" as const,
            ...(graphqlApiKey ? { apiKey: graphqlApiKey } : {}),
          },
        },
      }
    : {};

  // Two concrete literals (not a ternary union) so Amplify's Cognito config type
  // resolves cleanly to the right member.
  if (identityPoolId) {
    Amplify.configure({
      Auth: { Cognito: { userPoolId, userPoolClientId, identityPoolId, allowGuestAccess: true } },
      ...api,
    });
  } else {
    Amplify.configure({
      Auth: { Cognito: { userPoolId, userPoolClientId } },
      ...api,
    });
  }

  configured = true;
  return true;
}
