import { Amplify, type ResourcesConfig } from "aws-amplify";

// The generated outputs carry `model_introspection` — the schema description that
// `client.models.*` is built from. It is env-agnostic (schema shape, not endpoint
// values) so it is safe to bundle from this file regardless of which backend the
// EXPO_PUBLIC_* vars point at. The file is gitignored but regenerated by the
// Amplify CI backend phase (and `ampx sandbox`) before the web bundle is built.
import amplifyOutputs from "@/amplify_outputs.json";

/**
 * Amplify v6 runtime configuration, built from EXPO_PUBLIC_* env vars.
 *
 * Why env vars and not `import outputs from "../amplify_outputs.json"`? That file
 * is generated by `npx ampx sandbox`, is gitignored, and does not exist until the
 * backend is deployed — a static import of it would break the Metro bundle today.
 * Reading from env is bundle-safe and lets the Supabase build run untouched.
 *
 * After deploying, copy these from amplify_outputs.json into .env:
 *   user_pool_id            → EXPO_PUBLIC_COGNITO_USER_POOL_ID
 *   user_pool_client_id     → EXPO_PUBLIC_COGNITO_APP_CLIENT_ID
 *   identity_pool_id        → EXPO_PUBLIC_COGNITO_IDENTITY_POOL_ID
 *   data.url                → EXPO_PUBLIC_APPSYNC_ENDPOINT
 */
const region = process.env.EXPO_PUBLIC_AWS_REGION ?? "ap-southeast-2";
const userPoolId = process.env.EXPO_PUBLIC_COGNITO_USER_POOL_ID ?? "";
const userPoolClientId = process.env.EXPO_PUBLIC_COGNITO_APP_CLIENT_ID ?? "";
const identityPoolId = process.env.EXPO_PUBLIC_COGNITO_IDENTITY_POOL_ID ?? "";
const graphqlEndpoint = process.env.EXPO_PUBLIC_APPSYNC_ENDPOINT ?? "";
const graphqlApiKey = process.env.EXPO_PUBLIC_APPSYNC_API_KEY ?? "";

type ModelIntrospection = NonNullable<
  NonNullable<ResourcesConfig["API"]>["GraphQL"]
>["modelIntrospection"];

/**
 * Schema introspection that `client.models.*` is generated from. Without it the
 * data client has no `.models`, so every `Event.list()`/`Hub.list()` call throws
 * and screens silently render empty (0 Events / 0 Communities).
 */
const modelIntrospection = amplifyOutputs.data
  .model_introspection as unknown as ModelIntrospection;

/** True once real Cognito values are present (i.e. the backend is deployed). */
export const isAwsConfigured = Boolean(userPoolId && userPoolClientId);

/**
 * AppSync read auth mode tracker. Signed-in users go through Cognito User Pools
 * (satisfies `allow.owner()/authenticated()/group()`); signed-out visitors must
 * use the Identity Pool unauthenticated (IAM) role so the schema's
 * `allow.guest().to(["read"])` rules apply — otherwise guest reads fail with
 * "No federated jwt" and public pages show zeros. The AuthProvider keeps this in
 * sync via {@link setDataSignedIn}; it defaults to guest so the public-facing
 * shell works before (and without) any sign-in.
 */
let dataSignedIn = false;

/** Called by the AuthProvider whenever the Cognito session resolves/changes. */
export function setDataSignedIn(signedIn: boolean): void {
  dataSignedIn = signedIn;
}

/** Auth mode for data-client operations, chosen from the current session. */
export function getDataAuthMode(): "userPool" | "identityPool" {
  return dataSignedIn ? "userPool" : "identityPool";
}

let configured = false;

/**
 * Configure Amplify once. No-ops (returns false) when AWS isn't configured, so
 * importing/calling this on the Supabase build is harmless.
 */
export function configureAmplify(): boolean {
  if (configured) return true;
  if (!isAwsConfigured) return false;

  const api = graphqlEndpoint
    ? {
        API: {
          GraphQL: {
            endpoint: graphqlEndpoint,
            region,
            defaultAuthMode: "userPool" as const,
            modelIntrospection,
            ...(graphqlApiKey ? { apiKey: graphqlApiKey } : {}),
          },
        },
      }
    : {};

  // Two concrete literals (not a ternary union) so Amplify's Cognito config type
  // resolves cleanly to the right member.
  if (identityPoolId) {
    Amplify.configure({
      Auth: { Cognito: { userPoolId, userPoolClientId, identityPoolId, allowGuestAccess: true } },
      ...api,
    });
  } else {
    Amplify.configure({
      Auth: { Cognito: { userPoolId, userPoolClientId } },
      ...api,
    });
  }

  configured = true;
  return true;
}
