import { Amplify, type ResourcesConfig } from "aws-amplify";

// The generated outputs carry `model_introspection` — the schema description that
// `client.models.*` is built from. It is env-agnostic (schema shape, not endpoint
// values) so it is safe to bundle from this file regardless of which backend the
// EXPO_PUBLIC_* vars point at. The file is gitignored but regenerated by the
// Amplify CI backend phase (and `ampx sandbox`) before the web bundle is built.
import amplifyOutputs from "@/amplify_outputs.json";

/**
 * Resolve a config value: prefer the EXPO_PUBLIC_* env var; fall back to the
 * corresponding field in amplify_outputs.json.
 *
 * Exported as `resolveConfigField` for unit testing.
 */
function resolve(envValue: string, section: "auth" | "data", field: string): string {
  if (envValue) return envValue;
  try {
    const outputs = amplifyOutputs as unknown as Record<string, Record<string, string>>;
    return outputs[section]?.[field] ?? "";
  } catch {
    return "";
  }
}

export { resolve as resolveConfigField };

/**
 * Amplify v6 runtime configuration, built from EXPO_PUBLIC_* env vars with
 * automatic fallback to amplify_outputs.json when an env var is absent/empty.
 *
 * Priority order (highest first):
 *   1. EXPO_PUBLIC_* environment variables
 *   2. amplify_outputs.json (generated by `npx ampx sandbox` or CI backend phase)
 *
 * After deploying, copy these from amplify_outputs.json into .env:
 *   auth.user_pool_id            → EXPO_PUBLIC_COGNITO_USER_POOL_ID
 *   auth.user_pool_client_id     → EXPO_PUBLIC_COGNITO_APP_CLIENT_ID
 *   auth.identity_pool_id        → EXPO_PUBLIC_COGNITO_IDENTITY_POOL_ID
 *   data.url                     → EXPO_PUBLIC_APPSYNC_ENDPOINT
 *   auth.aws_region              → EXPO_PUBLIC_AWS_REGION
 */
const region =
  resolve(process.env.EXPO_PUBLIC_AWS_REGION ?? "", "auth", "aws_region") ||
  "ap-southeast-2";
const userPoolId = resolve(
  process.env.EXPO_PUBLIC_COGNITO_USER_POOL_ID ?? "",
  "auth",
  "user_pool_id",
);
const userPoolClientId = resolve(
  process.env.EXPO_PUBLIC_COGNITO_APP_CLIENT_ID ?? "",
  "auth",
  "user_pool_client_id",
);
const identityPoolId = resolve(
  process.env.EXPO_PUBLIC_COGNITO_IDENTITY_POOL_ID ?? "",
  "auth",
  "identity_pool_id",
);
const graphqlEndpoint = resolve(
  process.env.EXPO_PUBLIC_APPSYNC_ENDPOINT ?? "",
  "data",
  "url",
);
const graphqlApiKey = process.env.EXPO_PUBLIC_APPSYNC_API_KEY ?? "";

type ModelIntrospection = NonNullable<
  NonNullable<ResourcesConfig["API"]>["GraphQL"]
>["modelIntrospection"];

/**
 * Schema introspection that `client.models.*` is generated from. Without it the
 * data client has no `.models`, so every `Event.list()`/`Hub.list()` call throws
 * and screens silently render empty (0 Events / 0 Communities).
 */
const modelIntrospection = amplifyOutputs.data
  .model_introspection as unknown as ModelIntrospection;

/** True once real Cognito values are present (i.e. the backend is deployed). */
export const isAwsConfigured = Boolean(userPoolId && userPoolClientId);

/**
 * AppSync read auth mode tracker. Signed-in users go through Cognito User Pools
 * (satisfies `allow.owner()/authenticated()/group()`); signed-out visitors must
 * use the Identity Pool unauthenticated (IAM) role so the schema's
 * `allow.guest().to(["read"])` rules apply — otherwise guest reads fail with
 * "No federated jwt" and public pages show zeros. The AuthProvider keeps this in
 * sync via {@link setDataSignedIn}; it defaults to guest so the public-facing
 * shell works before (and without) any sign-in.
 */
let dataSignedIn = false;

/** Called by the AuthProvider whenever the Cognito session resolves/changes. */
export function setDataSignedIn(signedIn: boolean): void {
  dataSignedIn = signedIn;
}

/** Auth mode for data-client operations, chosen from the current session. */
export function getDataAuthMode(): "userPool" | "identityPool" {
  return dataSignedIn ? "userPool" : "identityPool";
}

// ─── Hot-reload fingerprint ────────────────────────────────────────────────

interface ConfigSnapshot {
  userPoolId: string;
  userPoolClientId: string;
  identityPoolId: string;
  graphqlEndpoint: string;
  region: string;
}

function buildFingerprint(cfg: ConfigSnapshot): string {
  return JSON.stringify(cfg);
}

let configured = false;
let configFingerprint: string | null = null;

// ─── configureAmplify ──────────────────────────────────────────────────────

/**
 * Configure Amplify once (idempotent in production; fingerprint-aware in dev).
 *
 * Returns `false` and logs an error when required Cognito values are missing
 * from both EXPO_PUBLIC_* env vars and amplify_outputs.json.
 */
export function configureAmplify(): boolean {
  const fingerprint = buildFingerprint({
    userPoolId,
    userPoolClientId,
    identityPoolId,
    graphqlEndpoint,
    region,
  });

  // In dev, re-configure whenever the resolved values change (hot-reload).
  // In production, the initial `configured` guard is sufficient.
  if (__DEV__) {
    if (configured && configFingerprint === fingerprint) return true;
  } else {
    if (configured) return true;
  }

  // Guard: required fields must be non-empty after dual-source resolution.
  if (!userPoolId || !userPoolClientId) {
    console.error(
      "[configureAmplify] Missing required Cognito values. Check EXPO_PUBLIC_* vars or amplify_outputs.json.",
    );
    return false;
  }

  const api = graphqlEndpoint
    ? {
        API: {
          GraphQL: {
            endpoint: graphqlEndpoint,
            region,
            defaultAuthMode: "userPool" as const,
            modelIntrospection,
            ...(graphqlApiKey ? { apiKey: graphqlApiKey } : {}),
          },
        },
      }
    : {};

  // Two concrete literals (not a ternary union) so Amplify's Cognito config type
  // resolves cleanly to the right member.
  if (identityPoolId) {
    Amplify.configure({
      Auth: { Cognito: { userPoolId, userPoolClientId, identityPoolId, allowGuestAccess: true } },
      ...api,
    });
  } else {
    console.warn(
      "[configureAmplify] No identityPoolId — guest reads will fail with 'No federated jwt'.",
    );
    Amplify.configure({
      Auth: { Cognito: { userPoolId, userPoolClientId } },
      ...api,
    });
  }

  configured = true;
  configFingerprint = fingerprint;
  return true;
}
