-- =============================================================================
-- CulturePass Australia — 07. Localities (suburb / postcode reference)
-- =============================================================================
-- Suburb + postcode lookup that powers the hub location picker ("enter your
-- suburb or postcode"). One row per (postcode, suburb): a single postcode maps
-- to many suburbs/localities. Read-only reference data, public SELECT only.
--
-- Source: Elkfox/Australian-Postcode-Data (au_postcodes.csv), itself derived
-- from GeoNames postal data. Seeded from supabase/seed_localities.sql which is
-- generated by scripts/extract-australian-localities.mjs.
-- =============================================================================

create table public.australian_localities (
  id           uuid primary key default gen_random_uuid(),
  postcode     text not null,                          -- 4-digit, zero-padded
  suburb       text not null,
  state_code   text not null references public.australian_states (code),
  latitude     numeric,
  longitude    numeric,
  coordinates  extensions.geography(point, 4326),
  created_at   timestamptz not null default now(),

  constraint australian_localities_postcode_suburb_state_key
    unique (postcode, suburb, state_code)
);

comment on table public.australian_localities is
  'Reference: Australian suburbs/localities keyed by postcode + state. '
  'Read-only to clients. Source: GeoNames via Elkfox/Australian-Postcode-Data.';

-- Lookup by postcode, fuzzy search by suburb name, plus spatial + state filters.
create index australian_localities_postcode_idx
  on public.australian_localities (postcode);
create index australian_localities_suburb_trgm_idx
  on public.australian_localities using gin (suburb extensions.gin_trgm_ops);
create index australian_localities_state_idx
  on public.australian_localities (state_code);
create index australian_localities_coordinates_idx
  on public.australian_localities using gist (coordinates);

-- -----------------------------------------------------------------------------
-- RLS: public read, no client writes (curated via seed / service role only).
-- -----------------------------------------------------------------------------
alter table public.australian_localities enable row level security;

create policy "Localities are viewable by everyone"
  on public.australian_localities for select
  to anon, authenticated
  using (true);

-- No INSERT/UPDATE/DELETE policies => clients cannot mutate reference data.
